spring:
  h2:
    console:
      enabled: true
      path: /h2
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password:
    driverClassName: org.h2.Driver

  flyway:
    location: classpath:db/migration
    table: schema_history

  security:
    jwt:
      keystore-location: keys/keystore.jks
      keystore-password: password
      key-alias: jwtsigning
      private-key-passphrase: password